"""Audit EVERY structurally available head subset for directed Exact-K transitions.

THIS IS A DIAGNOSTIC REPLAY, NOT THE TRAINED ATTENTION ROUTER.
The trained model uses nonlinear learned attention; its true individual
subset effects cannot be extracted from static averaging. Here we measure a
transparent direct-vote counterfactual on the SAME held-out expert outputs.
We therefore do not call individual subsets "causes" of neural errors.

For each fold, outputs are generated by experts fit only on the other folds;
inner OOF selection audits are computed separately on outer-train folds.
The full K0-K6 native frozen baseline is preserved. No corrective change.
"""
from __future__ import annotations

import argparse
import csv
import itertools
import json
from collections import defaultdict
from pathlib import Path

import numpy as np

from scripts.evaluate_v273_dynamic_heads import (
    EXPERTS, CLASSES, get_matrix, load_cohort, load_features,
    oof_experts, outer_experts
)
from scripts.yourmt3_exactk_common import FOLDS, metrics, require

HEAD_NAMES = ("H0", "H1", "H2", "H3", "H4", "H5",
              "C23", "C32", "C34", "C43")
CORRECTORS = {(2,3):6, (3,2):7, (3,4):8, (4,3):9}
SCENARIOS = tuple((b,k) for b in (2,3,4)
                  for k in range(7) if k!=b)
HEAD_COUNT = 6
ELIGIBLE_COUNT = 7493
EXPECTED_NATIVE = 59309


def structural_heads(base_k, target_k):
    if target_k in (0,1):
        return (0,)
    assert target_k in (2,3,4,5,6)
    return (*range(HEAD_COUNT), *((CORRECTORS[(base_k,target_k)],)
             if (base_k,target_k) in CORRECTORS else ()))


def all_nonempty(heads):
    return tuple(ids for n in range(1,len(heads)+1)
                 for ids in itertools.combinations(heads,n))


def votes(P, baseline_class, target_class, heads):
    """Vote to KEEP original K or replace by hypothetical candidate K.

    All voters are directly computed from the same frozen OOF and outer-fold
    expert probabilities. Keep scores include a specialist's KEEP evidence.
    'C' adapters use the explicit proposal probability q from the original
    14-head prototype. We do NOT fabricate other historical corrections.
    """
    n=len(P)
    require(P.shape==(n,6,5),"bad source posterior")
    p_keep=np.zeros((n,len(heads)),np.float64)
    p_target=np.zeros_like(p_keep)
    for c,h in enumerate(heads):
        if h<6:
            share=.78 if h==0 else .93
            p_keep[:,c]=share*P[:,h,baseline_class-2]+(1.-share)
            if target_class>=2:
                p_target[:,c]=share*P[:,h,target_class-2]
            else:
                # H0 has no learned K0/K1 posterior at all.
                p_target[:,c]=0.
        else:
            require(CORRECTORS[(baseline_class,target_class)]==h,
                    "unavailable transition adapter")
            q=np.mean(P[:,1:,target_class-2],axis=1)
            p_target[:,c]=.95*q
            p_keep[:,c]=1.-.95*q
    return p_keep,p_target


def probe(P, base_class, target, heads, subsets):
    stay,replace=votes(P,base_class,target,heads)
    incidence=np.asarray([[int(head in subset) for head in heads]
                          for subset in subsets],np.float64).T
    # 'mean' is a diagnostic NON-LEARNED explicit subset-voting rule.
    count=np.sum(incidence,axis=0)
    assert np.all(count>0)
    # n_events x n_combinations
    stay=np.matmul(stay,incidence)/count[None,:]
    replace=np.matmul(replace,incidence)/count[None,:]
    return replace>stay, (replace-stay)


def count(out, real, source, target):
    """7-way true-K audit for binary change-to-target decision."""
    result=dict(n=int(len(real)),changes=int(out.sum()))
    for k in range(7):
        row=(real==k)
        result[f"true_k{k}_events"]=int(row.sum())
        result[f"true_k{k}_corrections"]=int((out & row & (k==target)).sum())
        result[f"true_k{k}_regressions"]=int((out & row & (k==source)).sum())
        result[f"true_k{k}_neutral"]=int((out & row & (k!=source)&(k!=target)).sum())
    result["corrections"]=sum(result[f"true_k{k}_corrections"] for k in range(7))
    result["regressions"]=sum(result[f"true_k{k}_regressions"] for k in range(7))
    result["neutrals"]=result["changes"]-result["corrections"]-result["regressions"]
    result["net"]=result["corrections"]-result["regressions"]
    require(result["neutrals"]>=0,"invalid audit")
    return result


def run():
    p=argparse.ArgumentParser()
    p.add_argument("--cohort",type=Path,required=True)
    p.add_argument("--features",type=Path,required=True)
    p.add_argument("--output",type=Path,required=True)
    a=p.parse_args()
    require(not a.output.exists(),"no overwrite")
    y,base,ids,fold,member,starts=load_cohort(a.cohort)
    position,rows,feature_names,_=load_features(
        a.features,y,base,ids,fold,member,starts)
    require(len(y)==EXPECTED_NATIVE and len(position)==ELIGIBLE_COUNT,
            "native cohort unexpectedly changed")
    yc=y[position];bc=base[position];fc=fold[position]
    x={name:get_matrix(rows,feature_names,field,prefixes)
       for name,(field,prefixes) in EXPERTS.items()}

    configs={}
    for source,target in SCENARIOS:
        heads=structural_heads(source,target)
        subsets=all_nonempty(heads)
        require(len(subsets)==(2**len(heads)-1),"subset count mismatch")
        configs[(source,target)]=dict(heads=heads,subsets=subsets)
    # 4 directed adjacent moves x 127, 8 remaining poly moves x 63,
    # 6 non-poly moves x 1 = 1018 structural combinations.
    require(sum(len(v["subsets"]) for v in configs.values())==1018,
            "unexpected total subset inventory")
    fold_results=[]
    transitions={}
    for vf in FOLDS:
        train=fc!=vf;heldout=fc==vf
        require(train.any() and heldout.any(),"empty OOF fold")
        # OOF experts trained only on other inner folds. For each
        # outer-evaluation fold, held-out experts fit on full outer-train.
        ptr=oof_experts(
            {name:v[train] for name,v in x.items()},yc[train],bc[train],fc[train]
        )
        pv=outer_experts(
            {name:{"train":v[train],"test":v[heldout]}
             for name,v in x.items()},yc[train],bc[heldout]
        )
        for source,target in SCENARIOS:
            cfg=configs[(source,target)]
            for phase,indices,P in (
                ("train_OOF",train,ptr),
                ("heldout_diagnostic",heldout,pv)
            ):
                within=np.asarray(bc[indices]==source)
                sub_P=P[within]
                sub_y=yc[indices][within]
                outcomes,_=probe(sub_P,source,target,
                                 cfg["heads"],cfg["subsets"])
                for i,ids_ in enumerate(cfg["subsets"]):
                    record=dict(fold=int(vf),phase=phase,
                                original_K=source,target_K=target,
                                combination_id=f"{source}_to_{target}_S{i+1:03}",
                                head_count=len(ids_),
                                heads="+".join(HEAD_NAMES[h] for h in ids_),
                                **count(outcomes[:,i],sub_y,source,target))
                    fold_results.append(record)
        print(json.dumps({"completed_fold":int(vf),
                          "fold_audits":sum(1 for x in fold_results
                                            if x["fold"]==int(vf)),
                          "heldout":int(heldout.sum())}),flush=True)

    report=dict(
        experiment="v273_structural_subset_combinations_diagnostic",
        cohort={"native":len(y),"eligible":len(position),
                "folds":list(FOLDS),"player05_and_fold3_excluded":True},
        total_structural_selection_definitions=len(fold_results)//(2*len(FOLDS)),
        training_audit_records=sum(z["phase"]=="train_OOF" for z in fold_results),
        heldout_audit_records=sum(z["phase"]=="heldout_diagnostic"
                                 for z in fold_results),
        per_scenario={f"{b}->{k}":{
            "heads":[HEAD_NAMES[h] for h in configs[(b,k)]["heads"]],
            "selection_count":len(configs[(b,k)]["subsets"])
        } for b,k in SCENARIOS},
        critical_neural_decoder_observation={
            "K0_K1_heads_directly_compatible": ["H0"],
            "H0_K0_K1_class_evidence":0.0,
            "trained_neural_K0_K1_actions_in_previous_independent_forensics":1822,
            "previous_forensic_run":37748832939,
            "note":"The neural decoder's K0/K1 outputs cannot be attributed to any class-specific voting subset under this documented contract."
        },
        scientific_caveats=[
            "All direct subset outcomes computed as equal-weight KEEP-versus-target binary votes. This is NOT a replay of learned class attention interactions.",
            "No trained router decides which of the 127 subsets to choose; those effects remain UNIDENTIFIED by this audit.",
            "Outer validation fold labels used ONLY for descriptive held-out audit, not selection or tuning.",
            "Training OOF and heldout diagnostic audits are separate datasets.",
            "The candidate probability adapters do not represent independently trained historical correctors.",
            "K0/K1 have H0-only structural support, but H0 has no nonpoly class posterior; no structural subset can directly vote for K0/K1.",
            "KEEP-only fix heads have no direct K vote; excluded from these K-target structural subset counts.",
            "No automatic reference promotion; this is a diagnostic with a simplified subset-vote mechanism.",
        ]
    )
    aggregated=defaultdict(list)
    for z in fold_results:
        if z["phase"]=="heldout_diagnostic":
            aggregated[(z["original_K"],z["target_K"],z["combination_id"],
                        z["heads"])].append(z)
    summaries=[]
    total_trials=0
    for (b,k,uid,heads),parts in aggregated.items():
        require(len(parts)==len(FOLDS),"missing heldout subset")
        d={key:int(sum(p[key] for p in parts))
           for key in ("n","changes","corrections","regressions","neutrals","net")}
        d.update(original_K=b,target_K=k,combination_id=uid,
                 heads=heads,head_count=len(heads.split("+")))
        for actual in range(7):
            for metric in ("events","corrections","regressions","neutral"):
                z=f"true_k{actual}_{metric}"
                d[z]=int(sum(part[z] for part in parts))
        summaries.append(d)
        total_trials+=d["changes"]
    require(len(summaries)==1018,"heldout aggregate completeness")
    report["summary"]=dict(total_heldout_candidate_definitions=len(summaries),
                           total_actions_across_counterfactual_subsets=total_trials,
                           no_causal_attribution=True)
    report["scenarios_best_and_worst_direct_vote_DESCRIPTIVE_ONLY"]={}
    for b,k in SCENARIOS:
        group=[z for z in summaries if z["original_K"]==b and z["target_K"]==k]
        require(len(group)==len(configs[(b,k)]["subsets"]),"scenario completeness")
        report["scenarios_best_and_worst_direct_vote_DESCRIPTIVE_ONLY"][f"{b}->{k}"]={
            "selection_count":len(group),
            "best_net":sorted(group,key=lambda z:(-z["net"],z["regressions"]))[0],
            "worst_net":sorted(group,key=lambda z:(z["net"],-z["regressions"]))[0],
            "number_with_positive_net":int(sum(z["net"]>0 for z in group)),
            "number_with_negative_net":int(sum(z["net"]<0 for z in group)),
            "number_without_actions":int(sum(z["changes"]==0 for z in group)),
        }
    a.output.mkdir(parents=True)
    (a.output/"audit-structure.json").write_text(json.dumps(report,indent=2)+"\n")
    for name,records in [
        ("audits-individuels-OOF-et-heldout.csv",fold_results),
        ("audits-agreges-1018-selections.csv",summaries),
    ]:
        with (a.output/name).open("w",newline="") as f:
            fields=list(records[0])
            w=csv.DictWriter(f,fieldnames=fields)
            w.writeheader()
            w.writerows(records)
    lines=["# Audit exhaustif structurel de sélections par K",
           "",
           "Audit **diagnostique des votes directs** par sous-ensemble, "
           "pas audit causal du routeur neuronal à attention.",
           "",
           f"{len(summaries)} définitions de sous-ensembles admissibles "
           "sur tous les K de destination et origines K2/K3/K4.",
           "",
           "| Origine -> K visé | Têtes possibles | Sous-ensembles | "
           "Avec net positif | Avec net négatif | Sans modification |",
           "|---|---:|---:|---:|---:|---:|"]
    for b,k in SCENARIOS:
        d=report["scenarios_best_and_worst_direct_vote_DESCRIPTIVE_ONLY"][f"{b}->{k}"]
        lines.append(f"| K{b}->K{k} | {len(configs[(b,k)]['heads'])} | "
                     f"{d['selection_count']} | {d['number_with_positive_net']} | "
                     f"{d['number_with_negative_net']} | {d['number_without_actions']} |")
    lines+=["","## Diagnostic de K2 -> K1","",
            "Seule la tête H0 est admissible structurellement pour K1, "
            "sans véritable probabilité de K1. **Aucun des 127 sous-ensembles "
            "polyphoniques ne fournit une proposition directe vers K1.** "
            "Les 361 régressions K2->K1 sont émises par le décodeur neuronal "
            "libre (audit précédent), pas par des votes de ces 127 ensembles.",
            "",
            "## Détails des transitions principales (meilleur/pire vote direct, "
            "DESCRIPTIF, non sélectionné par l'algorithme)","",
            "| Transition | Choix | Têtes | Fix | Régressions | Net |",
            "|---|---|---|---:|---:|---:|"]
    for key in ["2->3","3->2","3->4","4->3"]:
        z=report["scenarios_best_and_worst_direct_vote_DESCRIPTIVE_ONLY"][key]
        for label,record in (("max net",z["best_net"]),("min net",z["worst_net"])):
            lines.append(f"| {key} | {label} | {record['heads']} | "
                         f"{record['corrections']} | {record['regressions']} | "
                         f"{record['net']:+d} |")
    lines+=["","## Limites cruciales"]+["- "+x for x in report["scientific_caveats"]]
    (a.output/"verdict.md").write_text("\n".join(lines)+"\n")
    print("\n".join(lines),flush=True)


if __name__=="__main__":
    run()
